version: "3.8"
services:
  django:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: estsoft-bookstore-django
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: estsoft-bookstore-nginx
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge